export type LinkItem = {
    id: string;
    user_id?: string;
    url: string;
    title: string;
    description?: string;
    domain: string;
    favicon_url: string;
    content_type?: string;
    extraction_status?: string;
    source?: string;
    status: "unread" | "read" | "skipped";
    is_favorite: boolean;
    reading_time_mins?: number;
    read_at?: string;
    created_at: string;
    updated_at?: string;
    deleted_at?: string | null;
    tags: string[];
};
